spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shootingplace"
    username: shootingplace
    password: uCqz@n]CmA%k#jR1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect