spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shootingPlace"
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: update